// ── Voice Line Library ──────────────────────────────────────────────────────
// 100+ premium voice lines for Kids Learning Fun.
// Every line is written as broadcast-quality children's media copy.

import type { VoiceProfileId } from './voiceProfiles';

// ── Types ──────────────────────────────────────────────────────────────────

export type LineCategory =
  | 'greeting'
  | 'encouragement'
  | 'celebration'
  | 'hint'
  | 'retry'
  | 'bedtime'
  | 'curiosity'
  | 'transition'
  | 'lesson-intro'
  | 'mistake-recovery'
  | 'song-intro'
  | 'story-intro'
  | 'goodbye';

export type EmotionTag =
  | 'calm'
  | 'excited'
  | 'gentle'
  | 'proud'
  | 'curious'
  | 'sleepy'
  | 'warm'
  | 'playful';

export type ContextTag =
  | 'first-session'
  | 'returning'
  | 'lesson-complete'
  | 'mistake'
  | 'story-time'
  | 'song-time'
  | 'bedtime'
  | 'morning'
  | 'end-of-day'
  | 'streak';

export type AgeGroup = '2-3' | '4-5' | '6-8' | 'all';

export interface VoiceLine {
  id: string;
  text: string;
  category: LineCategory;
  emotionTags: EmotionTag[];
  contextTags: ContextTag[];
  ageGroup: AgeGroup;
  /** Specific mascot, or undefined for the narrator */
  characterId?: string;
  voiceProfileId: VoiceProfileId;
  /** SSML-enriched version (valid SSML fragment) */
  ssml?: string;
  /** 1 = must-play priority, 5 = filler / variety */
  priority: number;
}

// ── Helper to build SSML ───────────────────────────────────────────────────

function ssml(text: string, opts?: { rate?: string; pitch?: string; vol?: string; breakMs?: number }): string {
  const inner = opts?.breakMs
    ? `<break time="${opts.breakMs}ms"/>${text}`
    : text;
  return `<speak><prosody rate="${opts?.rate ?? 'medium'}" pitch="${opts?.pitch ?? 'medium'}" volume="${opts?.vol ?? 'medium'}">${inner}</prosody></speak>`;
}

// ── Voice Lines ────────────────────────────────────────────────────────────

export const voiceLines: VoiceLine[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // GREETINGS (12 lines)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'greet-001',
    text: 'Good morning, sunshine! Ready for a wonderful day of learning?',
    category: 'greeting',
    emotionTags: ['warm', 'excited'],
    contextTags: ['morning'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('Good morning, sunshine! <break time="400ms"/> Ready for a wonderful day of learning?', { rate: '95%', pitch: '+8%' }),
    priority: 1,
  },
  {
    id: 'greet-002',
    text: 'Hello, hello! I am so happy you are here!',
    category: 'greeting',
    emotionTags: ['excited', 'warm'],
    contextTags: ['first-session'],
    ageGroup: '2-3',
    voiceProfileId: 'narrator',
    ssml: ssml('Hello, hello! <break time="300ms"/> I am <emphasis level="strong">so</emphasis> happy you are here!', { rate: '85%', pitch: '+10%' }),
    priority: 1,
  },
  {
    id: 'greet-003',
    text: 'Welcome back, superstar! I knew you would come back to play with us.',
    category: 'greeting',
    emotionTags: ['proud', 'warm'],
    contextTags: ['returning'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('Welcome back, superstar! <break time="400ms"/> I knew you would come back to play with us.', { rate: '92%', pitch: '+5%' }),
    priority: 1,
  },
  {
    id: 'greet-004',
    text: 'Hey there, friend! Leo here. Shall we learn something amazing together?',
    category: 'greeting',
    emotionTags: ['warm', 'curious'],
    contextTags: ['returning'],
    ageGroup: '4-5',
    characterId: 'leo',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Hey there, friend! <break time="200ms"/> Leo here. Shall we learn something <emphasis level="moderate">amazing</emphasis> together?', { rate: '100%', pitch: '+15%' }),
    priority: 2,
  },
  {
    id: 'greet-005',
    text: 'Hop hop hooray! You are here! Ruby has been bouncing around waiting for you!',
    category: 'greeting',
    emotionTags: ['excited', 'playful'],
    contextTags: ['returning'],
    ageGroup: 'all',
    characterId: 'ruby',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Hop hop hooray! <break time="200ms"/> You are here! Ruby has been bouncing around waiting for you!', { rate: '110%', pitch: '+18%' }),
    priority: 2,
  },
  {
    id: 'greet-006',
    text: 'Good evening, little one. The stars are out, and so are we.',
    category: 'greeting',
    emotionTags: ['calm', 'gentle'],
    contextTags: ['bedtime'],
    ageGroup: 'all',
    characterId: 'ollie',
    voiceProfileId: 'bedtime-narrator',
    ssml: ssml('Good evening, little one. <break time="600ms"/> The stars are out, <break time="300ms"/> and so are we.', { rate: '75%', pitch: '-5%', vol: 'soft' }),
    priority: 1,
  },
  {
    id: 'greet-007',
    text: 'Quack quack! Daisy is ready to make something beautiful with you today!',
    category: 'greeting',
    emotionTags: ['playful', 'excited'],
    contextTags: ['returning'],
    ageGroup: '4-5',
    characterId: 'daisy',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Quack quack! <break time="200ms"/> Daisy is ready to make something beautiful with you today!', { rate: '105%', pitch: '+12%' }),
    priority: 2,
  },
  {
    id: 'greet-008',
    text: 'Psst! Finn here. I found something really cool. Want to come explore?',
    category: 'greeting',
    emotionTags: ['curious', 'playful'],
    contextTags: ['returning'],
    ageGroup: '6-8',
    characterId: 'finn',
    voiceProfileId: 'mascot-host',
    ssml: ssml('<prosody volume="soft">Psst!</prosody> <break time="300ms"/> Finn here. I found something really cool. <break time="200ms"/> Want to come explore?', { rate: '98%', pitch: '+10%' }),
    priority: 2,
  },
  {
    id: 'greet-009',
    text: 'Look who it is! My favourite learner is back! Three days in a row, wow!',
    category: 'greeting',
    emotionTags: ['proud', 'excited'],
    contextTags: ['streak'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('Look who it is! <break time="200ms"/> My favourite learner is back! <break time="300ms"/> Three days in a row, <emphasis level="strong">wow!</emphasis>', { rate: '95%', pitch: '+10%' }),
    priority: 1,
  },
  {
    id: 'greet-010',
    text: 'Hi hi hi! Ready? Set? Let us GO!',
    category: 'greeting',
    emotionTags: ['excited', 'playful'],
    contextTags: ['morning'],
    ageGroup: '2-3',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Hi hi hi! <break time="200ms"/> Ready? <break time="200ms"/> Set? <break time="300ms"/> Let us <emphasis level="strong">GO!</emphasis>', { rate: '100%', pitch: '+15%' }),
    priority: 2,
  },
  {
    id: 'greet-011',
    text: 'Good afternoon, adventurer! The day is young and full of discoveries.',
    category: 'greeting',
    emotionTags: ['warm', 'curious'],
    contextTags: ['returning'],
    ageGroup: '6-8',
    voiceProfileId: 'narrator',
    ssml: ssml('Good afternoon, adventurer! <break time="400ms"/> The day is young and full of discoveries.', { rate: '92%', pitch: '+5%' }),
    priority: 3,
  },
  {
    id: 'greet-012',
    text: 'There you are! I have been saving the best fun just for you.',
    category: 'greeting',
    emotionTags: ['warm', 'playful'],
    contextTags: ['returning'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('There you are! <break time="300ms"/> I have been saving the best fun just for you.', { rate: '95%', pitch: '+6%' }),
    priority: 3,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ENCOURAGEMENTS (16 lines)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'enc-001',
    text: 'You are doing so well! Keep going, I believe in you!',
    category: 'encouragement',
    emotionTags: ['proud', 'warm'],
    contextTags: ['lesson-complete'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('You are doing <emphasis level="moderate">so well!</emphasis> <break time="300ms"/> Keep going, I believe in you!', { rate: '92%', pitch: '+8%' }),
    priority: 1,
  },
  {
    id: 'enc-002',
    text: 'Look at you go! Every try makes you a little bit stronger.',
    category: 'encouragement',
    emotionTags: ['proud', 'warm'],
    contextTags: ['mistake'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('Look at you go! <break time="300ms"/> Every try makes you a little bit stronger.', { rate: '90%', pitch: '+6%' }),
    priority: 1,
  },
  {
    id: 'enc-003',
    text: 'Your brain is getting bigger with every answer. Can you feel it?',
    category: 'encouragement',
    emotionTags: ['curious', 'playful'],
    contextTags: ['lesson-complete'],
    ageGroup: '4-5',
    voiceProfileId: 'narrator',
    ssml: ssml('Your brain is getting bigger with every answer. <break time="500ms"/> Can you feel it?', { rate: '90%', pitch: '+5%' }),
    priority: 2,
  },
  {
    id: 'enc-004',
    text: 'You tried really hard, and that is what matters most.',
    category: 'encouragement',
    emotionTags: ['gentle', 'warm'],
    contextTags: ['mistake'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('You tried really hard, <break time="400ms"/> and that is what matters most.', { rate: '88%', pitch: '+3%' }),
    priority: 1,
  },
  {
    id: 'enc-005',
    text: 'Wow, you did not give up! That makes you super brave.',
    category: 'encouragement',
    emotionTags: ['proud', 'excited'],
    contextTags: ['mistake'],
    ageGroup: '2-3',
    voiceProfileId: 'narrator',
    ssml: ssml('Wow, you did not give up! <break time="400ms"/> That makes you <emphasis level="strong">super brave.</emphasis>', { rate: '85%', pitch: '+10%' }),
    priority: 1,
  },
  {
    id: 'enc-006',
    text: 'I can see you thinking really hard. That is exactly how learning works!',
    category: 'encouragement',
    emotionTags: ['warm', 'curious'],
    contextTags: ['lesson-complete'],
    ageGroup: '6-8',
    voiceProfileId: 'narrator',
    ssml: ssml('I can see you thinking really hard. <break time="400ms"/> That is exactly how learning works!', { rate: '92%', pitch: '+5%' }),
    priority: 2,
  },
  {
    id: 'enc-007',
    text: 'ROAR! You are getting stronger and smarter every single day!',
    category: 'encouragement',
    emotionTags: ['excited', 'proud'],
    contextTags: ['streak'],
    ageGroup: 'all',
    characterId: 'leo',
    voiceProfileId: 'mascot-host',
    ssml: ssml('<emphasis level="strong">ROAR!</emphasis> <break time="200ms"/> You are getting stronger and smarter every single day!', { rate: '105%', pitch: '+15%' }),
    priority: 2,
  },
  {
    id: 'enc-008',
    text: 'Take your time. There is no hurry at all. I will wait right here with you.',
    category: 'encouragement',
    emotionTags: ['gentle', 'calm'],
    contextTags: ['mistake'],
    ageGroup: 'all',
    characterId: 'ollie',
    voiceProfileId: 'narrator',
    ssml: ssml('Take your time. <break time="500ms"/> There is no hurry at all. <break time="400ms"/> I will wait right here with you.', { rate: '85%', pitch: '+2%' }),
    priority: 1,
  },
  {
    id: 'enc-009',
    text: 'You know what? Mistakes are just stepping stones to something wonderful.',
    category: 'encouragement',
    emotionTags: ['warm', 'gentle'],
    contextTags: ['mistake'],
    ageGroup: '6-8',
    voiceProfileId: 'narrator',
    ssml: ssml('You know what? <break time="400ms"/> Mistakes are just stepping stones to something wonderful.', { rate: '90%', pitch: '+3%' }),
    priority: 2,
  },
  {
    id: 'enc-010',
    text: 'Almost there! Just a little bit more and you have got it!',
    category: 'encouragement',
    emotionTags: ['excited', 'warm'],
    contextTags: ['lesson-complete'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('Almost there! <break time="200ms"/> Just a little bit more and you have got it!', { rate: '95%', pitch: '+8%' }),
    priority: 1,
  },
  {
    id: 'enc-011',
    text: 'Good job, good job, good job! You are on a roll!',
    category: 'encouragement',
    emotionTags: ['excited', 'playful'],
    contextTags: ['streak'],
    ageGroup: '2-3',
    characterId: 'ruby',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Good job, good job, good job! <break time="200ms"/> You are on a roll!', { rate: '108%', pitch: '+15%' }),
    priority: 2,
  },
  {
    id: 'enc-012',
    text: 'Every explorer gets a little lost sometimes. That is how we find the best paths!',
    category: 'encouragement',
    emotionTags: ['warm', 'curious'],
    contextTags: ['mistake'],
    ageGroup: '6-8',
    characterId: 'finn',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Every explorer gets a little lost sometimes. <break time="400ms"/> That is how we find the best paths!', { rate: '95%', pitch: '+10%' }),
    priority: 3,
  },
  {
    id: 'enc-013',
    text: 'I love watching you learn. You make it look so fun!',
    category: 'encouragement',
    emotionTags: ['warm', 'proud'],
    contextTags: ['lesson-complete'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('I love watching you learn. <break time="300ms"/> You make it look so fun!', { rate: '92%', pitch: '+6%' }),
    priority: 3,
  },
  {
    id: 'enc-014',
    text: 'You are being so patient, and patience is a superpower!',
    category: 'encouragement',
    emotionTags: ['gentle', 'proud'],
    contextTags: ['mistake'],
    ageGroup: '4-5',
    voiceProfileId: 'narrator',
    ssml: ssml('You are being so patient, <break time="300ms"/> and patience is a <emphasis level="moderate">superpower!</emphasis>', { rate: '90%', pitch: '+5%' }),
    priority: 2,
  },
  {
    id: 'enc-015',
    text: 'That was a really clever try! Let us see what happens next.',
    category: 'encouragement',
    emotionTags: ['curious', 'warm'],
    contextTags: ['mistake'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('That was a really clever try! <break time="300ms"/> Let us see what happens next.', { rate: '92%', pitch: '+5%' }),
    priority: 2,
  },
  {
    id: 'enc-016',
    text: 'Remember, even the tallest trees started as tiny seeds. You are growing!',
    category: 'encouragement',
    emotionTags: ['gentle', 'warm'],
    contextTags: ['lesson-complete'],
    ageGroup: '6-8',
    voiceProfileId: 'narrator',
    ssml: ssml('Remember, even the tallest trees started as tiny seeds. <break time="500ms"/> You are growing!', { rate: '90%', pitch: '+3%' }),
    priority: 3,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CELEBRATIONS (12 lines)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'cel-001',
    text: 'You did it! That was absolutely fantastic!',
    category: 'celebration',
    emotionTags: ['excited', 'proud'],
    contextTags: ['lesson-complete'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('You did it! <break time="200ms"/> That was absolutely <emphasis level="strong">fantastic!</emphasis>', { rate: '100%', pitch: '+12%' }),
    priority: 1,
  },
  {
    id: 'cel-002',
    text: 'Hooray! You just earned a star! How sparkly!',
    category: 'celebration',
    emotionTags: ['excited', 'playful'],
    contextTags: ['lesson-complete'],
    ageGroup: '2-3',
    voiceProfileId: 'narrator',
    ssml: ssml('Hooray! <break time="200ms"/> You just earned a star! <break time="200ms"/> How sparkly!', { rate: '95%', pitch: '+12%' }),
    priority: 1,
  },
  {
    id: 'cel-003',
    text: 'That is three in a row! You are on fire today!',
    category: 'celebration',
    emotionTags: ['excited', 'proud'],
    contextTags: ['streak'],
    ageGroup: 'all',
    voiceProfileId: 'mascot-host',
    ssml: ssml('That is three in a row! <break time="200ms"/> You are on <emphasis level="strong">fire</emphasis> today!', { rate: '108%', pitch: '+15%' }),
    priority: 1,
  },
  {
    id: 'cel-004',
    text: 'WOW! Just wow! I cannot believe how amazing you are!',
    category: 'celebration',
    emotionTags: ['excited', 'proud'],
    contextTags: ['lesson-complete'],
    ageGroup: 'all',
    voiceProfileId: 'mascot-host',
    ssml: ssml('<emphasis level="strong">WOW!</emphasis> <break time="300ms"/> Just wow! <break time="200ms"/> I cannot believe how amazing you are!', { rate: '105%', pitch: '+18%' }),
    priority: 1,
  },
  {
    id: 'cel-005',
    text: 'Look at that! A brand new badge! You earned it fair and square.',
    category: 'celebration',
    emotionTags: ['proud', 'warm'],
    contextTags: ['lesson-complete'],
    ageGroup: '4-5',
    voiceProfileId: 'narrator',
    ssml: ssml('Look at that! <break time="300ms"/> A brand new badge! <break time="300ms"/> You earned it fair and square.', { rate: '95%', pitch: '+10%' }),
    priority: 1,
  },
  {
    id: 'cel-006',
    text: 'Champion! Champion! Champion! What an incredible job!',
    category: 'celebration',
    emotionTags: ['excited', 'proud'],
    contextTags: ['lesson-complete'],
    ageGroup: 'all',
    characterId: 'ruby',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Champion! Champion! Champion! <break time="200ms"/> What an <emphasis level="strong">incredible</emphasis> job!', { rate: '112%', pitch: '+18%' }),
    priority: 2,
  },
  {
    id: 'cel-007',
    text: 'That was perfect! Not a single mistake. You are a real pro.',
    category: 'celebration',
    emotionTags: ['proud', 'warm'],
    contextTags: ['lesson-complete'],
    ageGroup: '6-8',
    voiceProfileId: 'narrator',
    ssml: ssml('That was <emphasis level="strong">perfect!</emphasis> <break time="300ms"/> Not a single mistake. You are a real pro.', { rate: '95%', pitch: '+8%' }),
    priority: 2,
  },
  {
    id: 'cel-008',
    text: 'Yay yay yay! You are the best! Clap clap clap!',
    category: 'celebration',
    emotionTags: ['excited', 'playful'],
    contextTags: ['lesson-complete'],
    ageGroup: '2-3',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Yay yay yay! <break time="200ms"/> You are the best! <break time="200ms"/> Clap clap clap!', { rate: '100%', pitch: '+15%' }),
    priority: 2,
  },
  {
    id: 'cel-009',
    text: 'What a discovery! You figured that out all by yourself!',
    category: 'celebration',
    emotionTags: ['proud', 'curious'],
    contextTags: ['lesson-complete'],
    ageGroup: '4-5',
    characterId: 'finn',
    voiceProfileId: 'mascot-host',
    ssml: ssml('What a discovery! <break time="300ms"/> You figured that out all by yourself!', { rate: '100%', pitch: '+12%' }),
    priority: 2,
  },
  {
    id: 'cel-010',
    text: 'Hoot hoot! Well done, wise little learner. That took real thinking.',
    category: 'celebration',
    emotionTags: ['proud', 'warm'],
    contextTags: ['lesson-complete'],
    ageGroup: 'all',
    characterId: 'ollie',
    voiceProfileId: 'narrator',
    ssml: ssml('Hoot hoot! <break time="300ms"/> Well done, wise little learner. <break time="200ms"/> That took real thinking.', { rate: '90%', pitch: '+5%' }),
    priority: 2,
  },
  {
    id: 'cel-011',
    text: 'You have completed the whole lesson! That deserves a big round of applause!',
    category: 'celebration',
    emotionTags: ['excited', 'proud'],
    contextTags: ['lesson-complete'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('You have completed the whole lesson! <break time="400ms"/> That deserves a big round of applause!', { rate: '95%', pitch: '+10%' }),
    priority: 1,
  },
  {
    id: 'cel-012',
    text: 'Five stars! Five whole stars! You are glowing brighter than the sun!',
    category: 'celebration',
    emotionTags: ['excited', 'proud'],
    contextTags: ['lesson-complete', 'streak'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('Five stars! Five whole stars! <break time="300ms"/> You are glowing brighter than the sun!', { rate: '100%', pitch: '+12%' }),
    priority: 1,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // HINTS (10 lines)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'hint-001',
    text: 'Hmm, look carefully. The answer is hiding right there!',
    category: 'hint',
    emotionTags: ['curious', 'playful'],
    contextTags: ['mistake'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('Hmm, <break time="400ms"/> look carefully. The answer is hiding right there!', { rate: '88%', pitch: '+5%' }),
    priority: 1,
  },
  {
    id: 'hint-002',
    text: 'Here is a little clue: think about the sound it makes.',
    category: 'hint',
    emotionTags: ['curious', 'gentle'],
    contextTags: ['mistake'],
    ageGroup: '4-5',
    voiceProfileId: 'narrator',
    ssml: ssml('Here is a little clue: <break time="500ms"/> think about the sound it makes.', { rate: '88%', pitch: '+5%' }),
    priority: 1,
  },
  {
    id: 'hint-003',
    text: 'You are so close! Try looking at the colours. Which one matches?',
    category: 'hint',
    emotionTags: ['warm', 'curious'],
    contextTags: ['mistake'],
    ageGroup: '2-3',
    voiceProfileId: 'narrator',
    ssml: ssml('You are so close! <break time="400ms"/> Try looking at the colours. Which one matches?', { rate: '85%', pitch: '+8%' }),
    priority: 1,
  },
  {
    id: 'hint-004',
    text: 'Let me give you a tiny nudge. Count them one more time, nice and slow.',
    category: 'hint',
    emotionTags: ['gentle', 'warm'],
    contextTags: ['mistake'],
    ageGroup: '4-5',
    voiceProfileId: 'narrator',
    ssml: ssml('Let me give you a tiny nudge. <break time="400ms"/> Count them one more time, nice and slow.', { rate: '85%', pitch: '+3%' }),
    priority: 2,
  },
  {
    id: 'hint-005',
    text: 'Psst! I spy the answer. It starts with the same sound as your name!',
    category: 'hint',
    emotionTags: ['playful', 'curious'],
    contextTags: ['mistake'],
    ageGroup: '6-8',
    voiceProfileId: 'mascot-host',
    ssml: ssml('<prosody volume="soft">Psst!</prosody> <break time="300ms"/> I spy the answer. It starts with the same sound as your name!', { rate: '95%', pitch: '+10%' }),
    priority: 2,
  },
  {
    id: 'hint-006',
    text: 'What shape has this many sides? Point to each side and count!',
    category: 'hint',
    emotionTags: ['curious', 'warm'],
    contextTags: ['mistake'],
    ageGroup: '4-5',
    voiceProfileId: 'narrator',
    ssml: ssml('What shape has this many sides? <break time="500ms"/> Point to each side and count!', { rate: '88%', pitch: '+5%' }),
    priority: 2,
  },
  {
    id: 'hint-007',
    text: 'Remember what we learned before? This one is just like that, only a little different!',
    category: 'hint',
    emotionTags: ['warm', 'gentle'],
    contextTags: ['mistake'],
    ageGroup: '6-8',
    voiceProfileId: 'narrator',
    ssml: ssml('Remember what we learned before? <break time="400ms"/> This one is just like that, only a little different!', { rate: '90%', pitch: '+5%' }),
    priority: 3,
  },
  {
    id: 'hint-008',
    text: 'Try touching each one. Which one feels right to you?',
    category: 'hint',
    emotionTags: ['gentle', 'curious'],
    contextTags: ['mistake'],
    ageGroup: '2-3',
    voiceProfileId: 'narrator',
    ssml: ssml('Try touching each one. <break time="500ms"/> Which one feels right to you?', { rate: '82%', pitch: '+5%' }),
    priority: 2,
  },
  {
    id: 'hint-009',
    text: 'Think about it like a puzzle. What piece is missing?',
    category: 'hint',
    emotionTags: ['curious', 'warm'],
    contextTags: ['mistake'],
    ageGroup: '6-8',
    voiceProfileId: 'narrator',
    ssml: ssml('Think about it like a puzzle. <break time="500ms"/> What piece is missing?', { rate: '90%', pitch: '+3%' }),
    priority: 3,
  },
  {
    id: 'hint-010',
    text: 'Ooh, I think I see it! Look at the very first one again.',
    category: 'hint',
    emotionTags: ['playful', 'curious'],
    contextTags: ['mistake'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('Ooh, I think I see it! <break time="400ms"/> Look at the very first one again.', { rate: '92%', pitch: '+8%' }),
    priority: 2,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // RETRY SUPPORT (10 lines)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'retry-001',
    text: 'Oops! Not quite, but that was a really good try. Let us go again!',
    category: 'retry',
    emotionTags: ['warm', 'gentle'],
    contextTags: ['mistake'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('Oops! <break time="200ms"/> Not quite, but that was a really good try. <break time="300ms"/> Let us go again!', { rate: '90%', pitch: '+5%' }),
    priority: 1,
  },
  {
    id: 'retry-002',
    text: 'Almost! You are so close I can feel it! One more time?',
    category: 'retry',
    emotionTags: ['excited', 'warm'],
    contextTags: ['mistake'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('Almost! <break time="200ms"/> You are so close I can feel it! <break time="300ms"/> One more time?', { rate: '92%', pitch: '+8%' }),
    priority: 1,
  },
  {
    id: 'retry-003',
    text: 'That is not the one, but I love that you tried! Shall we try again together?',
    category: 'retry',
    emotionTags: ['gentle', 'warm'],
    contextTags: ['mistake'],
    ageGroup: '2-3',
    voiceProfileId: 'narrator',
    ssml: ssml('That is not the one, <break time="300ms"/> but I love that you tried! <break time="300ms"/> Shall we try again together?', { rate: '85%', pitch: '+5%' }),
    priority: 1,
  },
  {
    id: 'retry-004',
    text: 'Not this time, but guess what? You are learning even from the tricky ones!',
    category: 'retry',
    emotionTags: ['warm', 'proud'],
    contextTags: ['mistake'],
    ageGroup: '4-5',
    voiceProfileId: 'narrator',
    ssml: ssml('Not this time, <break time="300ms"/> but guess what? You are learning even from the tricky ones!', { rate: '90%', pitch: '+5%' }),
    priority: 1,
  },
  {
    id: 'retry-005',
    text: 'Good guess! That was not it, but every guess gets you closer. Try again!',
    category: 'retry',
    emotionTags: ['warm', 'curious'],
    contextTags: ['mistake'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('Good guess! <break time="200ms"/> That was not it, but every guess gets you closer. <break time="200ms"/> Try again!', { rate: '92%', pitch: '+5%' }),
    priority: 2,
  },
  {
    id: 'retry-006',
    text: 'Hmm, that one is tricky, is it not? No worries! Let us look at it together.',
    category: 'retry',
    emotionTags: ['gentle', 'warm'],
    contextTags: ['mistake'],
    ageGroup: '4-5',
    voiceProfileId: 'narrator',
    ssml: ssml('Hmm, that one is tricky, is it not? <break time="400ms"/> No worries! Let us look at it together.', { rate: '88%', pitch: '+3%' }),
    priority: 2,
  },
  {
    id: 'retry-007',
    text: 'Whoopsie! That happens to the best of us. Ready for another go?',
    category: 'retry',
    emotionTags: ['playful', 'warm'],
    contextTags: ['mistake'],
    ageGroup: '2-3',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Whoopsie! <break time="300ms"/> That happens to the best of us. <break time="300ms"/> Ready for another go?', { rate: '90%', pitch: '+10%' }),
    priority: 2,
  },
  {
    id: 'retry-008',
    text: 'Not quite right, but you know what is great? You did not give up. That is what champions do.',
    category: 'retry',
    emotionTags: ['proud', 'warm'],
    contextTags: ['mistake'],
    ageGroup: '6-8',
    voiceProfileId: 'narrator',
    ssml: ssml('Not quite right, <break time="300ms"/> but you know what is great? <break time="400ms"/> You did not give up. That is what champions do.', { rate: '90%', pitch: '+5%' }),
    priority: 2,
  },
  {
    id: 'retry-009',
    text: 'Try, try, try again! The more you try, the more you learn!',
    category: 'retry',
    emotionTags: ['playful', 'excited'],
    contextTags: ['mistake'],
    ageGroup: '2-3',
    characterId: 'ruby',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Try, try, try again! <break time="200ms"/> The more you try, the more you learn!', { rate: '105%', pitch: '+15%' }),
    priority: 2,
  },
  {
    id: 'retry-010',
    text: 'That was a brave attempt! Scientists try lots of times before they find the answer. Keep experimenting!',
    category: 'retry',
    emotionTags: ['curious', 'warm'],
    contextTags: ['mistake'],
    ageGroup: '6-8',
    characterId: 'finn',
    voiceProfileId: 'mascot-host',
    ssml: ssml('That was a brave attempt! <break time="300ms"/> Scientists try lots of times before they find the answer. <break time="200ms"/> Keep experimenting!', { rate: '95%', pitch: '+8%' }),
    priority: 3,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BEDTIME (10 lines)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'bed-001',
    text: 'The moon is rising, the stars are twinkling, and it is time to rest those bright eyes.',
    category: 'bedtime',
    emotionTags: ['sleepy', 'calm'],
    contextTags: ['bedtime'],
    ageGroup: 'all',
    characterId: 'ollie',
    voiceProfileId: 'bedtime-narrator',
    ssml: ssml('The moon is rising, <break time="500ms"/> the stars are twinkling, <break time="500ms"/> and it is time to rest those bright eyes.', { rate: '72%', pitch: '-5%', vol: 'soft' }),
    priority: 1,
  },
  {
    id: 'bed-002',
    text: 'Close your eyes. Take a deep breath in, and let it out slowly. Wonderful.',
    category: 'bedtime',
    emotionTags: ['calm', 'gentle'],
    contextTags: ['bedtime'],
    ageGroup: 'all',
    voiceProfileId: 'bedtime-narrator',
    ssml: ssml('Close your eyes. <break time="800ms"/> Take a deep breath in, <break time="1200ms"/> and let it out slowly. <break time="600ms"/> Wonderful.', { rate: '70%', pitch: '-5%', vol: 'soft' }),
    priority: 1,
  },
  {
    id: 'bed-003',
    text: 'You did so many wonderful things today. Now it is time for your body and your brain to rest.',
    category: 'bedtime',
    emotionTags: ['gentle', 'warm'],
    contextTags: ['bedtime', 'end-of-day'],
    ageGroup: 'all',
    voiceProfileId: 'bedtime-narrator',
    ssml: ssml('You did so many wonderful things today. <break time="700ms"/> Now it is time for your body <break time="300ms"/> and your brain <break time="300ms"/> to rest.', { rate: '72%', pitch: '-3%', vol: 'soft' }),
    priority: 1,
  },
  {
    id: 'bed-004',
    text: 'Hoot hoot. Ollie is getting sleepy too. Shall we listen to a story together?',
    category: 'bedtime',
    emotionTags: ['sleepy', 'warm'],
    contextTags: ['bedtime', 'story-time'],
    ageGroup: 'all',
    characterId: 'ollie',
    voiceProfileId: 'bedtime-narrator',
    ssml: ssml('Hoot hoot. <break time="500ms"/> Ollie is getting sleepy too. <break time="600ms"/> Shall we listen to a story together?', { rate: '72%', pitch: '-5%', vol: 'soft' }),
    priority: 1,
  },
  {
    id: 'bed-005',
    text: 'Imagine you are floating on a soft, fluffy cloud. The sky is warm and safe.',
    category: 'bedtime',
    emotionTags: ['calm', 'sleepy'],
    contextTags: ['bedtime'],
    ageGroup: '2-3',
    voiceProfileId: 'bedtime-narrator',
    ssml: ssml('Imagine you are floating <break time="500ms"/> on a soft, fluffy cloud. <break time="700ms"/> The sky is warm <break time="300ms"/> and safe.', { rate: '68%', pitch: '-5%', vol: 'soft' }),
    priority: 2,
  },
  {
    id: 'bed-006',
    text: 'The whole world is getting quiet now. Can you hear the hush? Shhhh.',
    category: 'bedtime',
    emotionTags: ['calm', 'gentle'],
    contextTags: ['bedtime'],
    ageGroup: '4-5',
    voiceProfileId: 'bedtime-narrator',
    ssml: ssml('The whole world is getting quiet now. <break time="600ms"/> Can you hear the hush? <break time="800ms"/> Shhhh.', { rate: '70%', pitch: '-5%', vol: 'x-soft' }),
    priority: 2,
  },
  {
    id: 'bed-007',
    text: 'Sweet dreams, little one. Tomorrow we will have another adventure together.',
    category: 'bedtime',
    emotionTags: ['warm', 'sleepy'],
    contextTags: ['bedtime', 'end-of-day'],
    ageGroup: 'all',
    voiceProfileId: 'bedtime-narrator',
    ssml: ssml('Sweet dreams, little one. <break time="800ms"/> Tomorrow we will have another adventure together.', { rate: '70%', pitch: '-5%', vol: 'soft' }),
    priority: 1,
  },
  {
    id: 'bed-008',
    text: 'Your favourite friends are all asleep. Leo is dreaming of letters. Daisy is dreaming of rainbows. And Ollie is right here with you.',
    category: 'bedtime',
    emotionTags: ['calm', 'warm'],
    contextTags: ['bedtime'],
    ageGroup: '2-3',
    voiceProfileId: 'bedtime-narrator',
    ssml: ssml('Your favourite friends are all asleep. <break time="600ms"/> Leo is dreaming of letters. <break time="500ms"/> Daisy is dreaming of rainbows. <break time="500ms"/> And Ollie is right here with you.', { rate: '68%', pitch: '-5%', vol: 'soft' }),
    priority: 2,
  },
  {
    id: 'bed-009',
    text: 'As the night wraps around you like a cosy blanket, remember how much you learned today. You are wonderful.',
    category: 'bedtime',
    emotionTags: ['gentle', 'warm'],
    contextTags: ['bedtime', 'end-of-day'],
    ageGroup: '6-8',
    voiceProfileId: 'bedtime-narrator',
    ssml: ssml('As the night wraps around you <break time="400ms"/> like a cosy blanket, <break time="500ms"/> remember how much you learned today. <break time="600ms"/> You are wonderful.', { rate: '72%', pitch: '-3%', vol: 'soft' }),
    priority: 2,
  },
  {
    id: 'bed-010',
    text: 'Goodnight, goodnight. See you in the morning light.',
    category: 'bedtime',
    emotionTags: ['sleepy', 'gentle'],
    contextTags: ['bedtime', 'end-of-day'],
    ageGroup: 'all',
    voiceProfileId: 'bedtime-narrator',
    ssml: ssml('Goodnight, goodnight. <break time="800ms"/> See you in the morning light.', { rate: '68%', pitch: '-5%', vol: 'x-soft' }),
    priority: 1,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CURIOSITY (8 lines)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'cur-001',
    text: 'I wonder what would happen if we tried this one! Shall we find out?',
    category: 'curiosity',
    emotionTags: ['curious', 'playful'],
    contextTags: ['lesson-complete'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('I wonder what would happen if we tried this one! <break time="500ms"/> Shall we find out?', { rate: '92%', pitch: '+8%' }),
    priority: 2,
  },
  {
    id: 'cur-002',
    text: 'Did you know that? Wow, the world is full of amazing things!',
    category: 'curiosity',
    emotionTags: ['excited', 'curious'],
    contextTags: ['lesson-complete'],
    ageGroup: '4-5',
    voiceProfileId: 'narrator',
    ssml: ssml('Did you know that? <break time="400ms"/> Wow, the world is full of amazing things!', { rate: '92%', pitch: '+10%' }),
    priority: 2,
  },
  {
    id: 'cur-003',
    text: 'Oooh, what is hiding over here? Let us go and look!',
    category: 'curiosity',
    emotionTags: ['curious', 'playful'],
    contextTags: ['returning'],
    ageGroup: '2-3',
    characterId: 'finn',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Oooh, what is hiding over here? <break time="400ms"/> Let us go and look!', { rate: '95%', pitch: '+12%' }),
    priority: 2,
  },
  {
    id: 'cur-004',
    text: 'Here is a fun question: can you think of something else that looks like this?',
    category: 'curiosity',
    emotionTags: ['curious', 'warm'],
    contextTags: ['lesson-complete'],
    ageGroup: '6-8',
    voiceProfileId: 'narrator',
    ssml: ssml('Here is a fun question: <break time="500ms"/> can you think of something else that looks like this?', { rate: '90%', pitch: '+5%' }),
    priority: 3,
  },
  {
    id: 'cur-005',
    text: 'I just learned something new too! We are learning together!',
    category: 'curiosity',
    emotionTags: ['excited', 'warm'],
    contextTags: ['lesson-complete'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('I just learned something new too! <break time="300ms"/> We are learning together!', { rate: '95%', pitch: '+8%' }),
    priority: 3,
  },
  {
    id: 'cur-006',
    text: 'Have you ever seen one of these in real life? Keep your eyes open today!',
    category: 'curiosity',
    emotionTags: ['curious', 'playful'],
    contextTags: ['lesson-complete'],
    ageGroup: '4-5',
    characterId: 'finn',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Have you ever seen one of these in real life? <break time="400ms"/> Keep your eyes open today!', { rate: '98%', pitch: '+10%' }),
    priority: 3,
  },
  {
    id: 'cur-007',
    text: 'Why do you think that happens? What a great thing to wonder about!',
    category: 'curiosity',
    emotionTags: ['curious', 'warm'],
    contextTags: ['lesson-complete'],
    ageGroup: '6-8',
    voiceProfileId: 'narrator',
    ssml: ssml('Why do you think that happens? <break time="500ms"/> What a great thing to wonder about!', { rate: '90%', pitch: '+5%' }),
    priority: 3,
  },
  {
    id: 'cur-008',
    text: 'Whoa, that is interesting! Do you want to know more?',
    category: 'curiosity',
    emotionTags: ['excited', 'curious'],
    contextTags: ['lesson-complete'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('Whoa, that is interesting! <break time="400ms"/> Do you want to know more?', { rate: '95%', pitch: '+10%' }),
    priority: 2,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TRANSITIONS (8 lines)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'trans-001',
    text: 'Great work! Now let us try something a little different.',
    category: 'transition',
    emotionTags: ['warm', 'curious'],
    contextTags: ['lesson-complete'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('Great work! <break time="400ms"/> Now let us try something a little different.', { rate: '92%', pitch: '+5%' }),
    priority: 1,
  },
  {
    id: 'trans-002',
    text: 'Ready for the next adventure? Here we go!',
    category: 'transition',
    emotionTags: ['excited', 'playful'],
    contextTags: ['lesson-complete'],
    ageGroup: 'all',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Ready for the next adventure? <break time="300ms"/> Here we go!', { rate: '100%', pitch: '+12%' }),
    priority: 1,
  },
  {
    id: 'trans-003',
    text: 'Ooh, I have something special to show you next. Come on!',
    category: 'transition',
    emotionTags: ['playful', 'curious'],
    contextTags: ['lesson-complete'],
    ageGroup: '4-5',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Ooh, I have something special to show you next. <break time="300ms"/> Come on!', { rate: '100%', pitch: '+12%' }),
    priority: 2,
  },
  {
    id: 'trans-004',
    text: 'You finished that one perfectly. What shall we do next?',
    category: 'transition',
    emotionTags: ['warm', 'proud'],
    contextTags: ['lesson-complete'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('You finished that one perfectly. <break time="400ms"/> What shall we do next?', { rate: '92%', pitch: '+5%' }),
    priority: 2,
  },
  {
    id: 'trans-005',
    text: 'Up, up, and away! On to the next one!',
    category: 'transition',
    emotionTags: ['excited', 'playful'],
    contextTags: ['lesson-complete'],
    ageGroup: '2-3',
    characterId: 'ruby',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Up, up, and away! <break time="200ms"/> On to the next one!', { rate: '108%', pitch: '+15%' }),
    priority: 2,
  },
  {
    id: 'trans-006',
    text: 'Let us take a little journey to the next challenge. Follow me!',
    category: 'transition',
    emotionTags: ['curious', 'playful'],
    contextTags: ['lesson-complete'],
    ageGroup: '4-5',
    characterId: 'finn',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Let us take a little journey to the next challenge. <break time="300ms"/> Follow me!', { rate: '100%', pitch: '+10%' }),
    priority: 3,
  },
  {
    id: 'trans-007',
    text: 'And now, for something really exciting...',
    category: 'transition',
    emotionTags: ['excited', 'curious'],
    contextTags: ['lesson-complete'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('And now, <break time="500ms"/> for something really exciting...', { rate: '88%', pitch: '+8%' }),
    priority: 2,
  },
  {
    id: 'trans-008',
    text: 'Time for a new game! This one is going to be so much fun!',
    category: 'transition',
    emotionTags: ['excited', 'playful'],
    contextTags: ['lesson-complete'],
    ageGroup: 'all',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Time for a new game! <break time="300ms"/> This one is going to be <emphasis level="moderate">so</emphasis> much fun!', { rate: '105%', pitch: '+12%' }),
    priority: 2,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // LESSON INTROS (7 lines)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'les-001',
    text: 'Today we are going to learn something really cool. Are you ready? Let us go!',
    category: 'lesson-intro',
    emotionTags: ['excited', 'warm'],
    contextTags: ['first-session'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('Today we are going to learn something really cool. <break time="500ms"/> Are you ready? <break time="300ms"/> Let us go!', { rate: '92%', pitch: '+8%' }),
    priority: 1,
  },
  {
    id: 'les-002',
    text: 'Let us start with something fun! Can you see what is on the screen?',
    category: 'lesson-intro',
    emotionTags: ['warm', 'curious'],
    contextTags: ['first-session'],
    ageGroup: '2-3',
    voiceProfileId: 'narrator',
    ssml: ssml('Let us start with something fun! <break time="400ms"/> Can you see what is on the screen?', { rate: '85%', pitch: '+8%' }),
    priority: 1,
  },
  {
    id: 'les-003',
    text: 'Welcome to today is lesson! We are going to explore, discover, and have a great time.',
    category: 'lesson-intro',
    emotionTags: ['warm', 'excited'],
    contextTags: ['returning'],
    ageGroup: '4-5',
    voiceProfileId: 'narrator',
    ssml: ssml('Welcome to today\'s lesson! <break time="400ms"/> We are going to explore, discover, and have a great time.', { rate: '92%', pitch: '+6%' }),
    priority: 1,
  },
  {
    id: 'les-004',
    text: 'Alright, adventurers! Put your thinking caps on. We have got something brilliant ahead.',
    category: 'lesson-intro',
    emotionTags: ['excited', 'curious'],
    contextTags: ['returning'],
    ageGroup: '6-8',
    voiceProfileId: 'narrator',
    ssml: ssml('Alright, adventurers! <break time="300ms"/> Put your thinking caps on. <break time="400ms"/> We have got something brilliant ahead.', { rate: '95%', pitch: '+8%' }),
    priority: 1,
  },
  {
    id: 'les-005',
    text: 'ROAR! Leo is so excited to teach you this one! Listen up, friend!',
    category: 'lesson-intro',
    emotionTags: ['excited', 'warm'],
    contextTags: ['returning'],
    ageGroup: 'all',
    characterId: 'leo',
    voiceProfileId: 'mascot-host',
    ssml: ssml('<emphasis level="strong">ROAR!</emphasis> <break time="200ms"/> Leo is so excited to teach you this one! <break time="200ms"/> Listen up, friend!', { rate: '105%', pitch: '+15%' }),
    priority: 2,
  },
  {
    id: 'les-006',
    text: 'Alright! First, let us look at this together. Then you get to try!',
    category: 'lesson-intro',
    emotionTags: ['warm', 'playful'],
    contextTags: ['first-session'],
    ageGroup: '4-5',
    voiceProfileId: 'narrator',
    ssml: ssml('Alright! <break time="300ms"/> First, let us look at this together. <break time="400ms"/> Then you get to try!', { rate: '92%', pitch: '+6%' }),
    priority: 2,
  },
  {
    id: 'les-007',
    text: 'Look look look! Something new! Can you guess what it is?',
    category: 'lesson-intro',
    emotionTags: ['excited', 'curious'],
    contextTags: ['first-session'],
    ageGroup: '2-3',
    voiceProfileId: 'narrator',
    ssml: ssml('Look look look! <break time="300ms"/> Something new! <break time="500ms"/> Can you guess what it is?', { rate: '85%', pitch: '+10%' }),
    priority: 2,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MISTAKE RECOVERY (7 lines)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'mis-001',
    text: 'That is a great guess! The answer is a little different though. Let me show you.',
    category: 'mistake-recovery',
    emotionTags: ['gentle', 'warm'],
    contextTags: ['mistake'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('That is a great guess! <break time="400ms"/> The answer is a little different though. <break time="300ms"/> Let me show you.', { rate: '88%', pitch: '+3%' }),
    priority: 1,
  },
  {
    id: 'mis-002',
    text: 'Not quite, but that is okay! Even I get things wrong sometimes. Here, look at this.',
    category: 'mistake-recovery',
    emotionTags: ['warm', 'gentle'],
    contextTags: ['mistake'],
    ageGroup: '4-5',
    voiceProfileId: 'narrator',
    ssml: ssml('Not quite, but that is okay! <break time="300ms"/> Even I get things wrong sometimes. <break time="400ms"/> Here, look at this.', { rate: '88%', pitch: '+3%' }),
    priority: 1,
  },
  {
    id: 'mis-003',
    text: 'Oops-a-daisy! Let us try that one again. I will help you this time.',
    category: 'mistake-recovery',
    emotionTags: ['playful', 'gentle'],
    contextTags: ['mistake'],
    ageGroup: '2-3',
    characterId: 'daisy',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Oops-a-daisy! <break time="300ms"/> Let us try that one again. <break time="300ms"/> I will help you this time.', { rate: '90%', pitch: '+10%' }),
    priority: 1,
  },
  {
    id: 'mis-004',
    text: 'Almost right! You got the hard part. Let us just fix this little bit.',
    category: 'mistake-recovery',
    emotionTags: ['warm', 'proud'],
    contextTags: ['mistake'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('Almost right! <break time="300ms"/> You got the hard part. <break time="300ms"/> Let us just fix this little bit.', { rate: '90%', pitch: '+5%' }),
    priority: 1,
  },
  {
    id: 'mis-005',
    text: 'Interesting choice! That one was tricky. Here is how it works.',
    category: 'mistake-recovery',
    emotionTags: ['curious', 'warm'],
    contextTags: ['mistake'],
    ageGroup: '6-8',
    voiceProfileId: 'narrator',
    ssml: ssml('Interesting choice! <break time="400ms"/> That one was tricky. <break time="300ms"/> Here is how it works.', { rate: '92%', pitch: '+5%' }),
    priority: 2,
  },
  {
    id: 'mis-006',
    text: 'No no no, but yes yes yes to trying! Let us look at it together, okay?',
    category: 'mistake-recovery',
    emotionTags: ['playful', 'warm'],
    contextTags: ['mistake'],
    ageGroup: '2-3',
    voiceProfileId: 'mascot-host',
    ssml: ssml('No no no, <break time="200ms"/> but <emphasis level="moderate">yes yes yes</emphasis> to trying! <break time="300ms"/> Let us look at it together, okay?', { rate: '90%', pitch: '+12%' }),
    priority: 2,
  },
  {
    id: 'mis-007',
    text: 'That was not the one, but you were thinking in the right direction! Let me guide you.',
    category: 'mistake-recovery',
    emotionTags: ['gentle', 'warm'],
    contextTags: ['mistake'],
    ageGroup: '6-8',
    voiceProfileId: 'narrator',
    ssml: ssml('That was not the one, <break time="300ms"/> but you were thinking in the right direction! <break time="300ms"/> Let me guide you.', { rate: '90%', pitch: '+3%' }),
    priority: 2,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SONG INTROS (5 lines)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'song-001',
    text: 'It is singing time! Everybody ready? One, two, three!',
    category: 'song-intro',
    emotionTags: ['excited', 'playful'],
    contextTags: ['song-time'],
    ageGroup: 'all',
    voiceProfileId: 'song-leader',
    ssml: ssml('It is singing time! <break time="300ms"/> Everybody ready? <break time="200ms"/> One, <break time="200ms"/> two, <break time="200ms"/> three!', { rate: '105%', pitch: '+15%' }),
    priority: 1,
  },
  {
    id: 'song-002',
    text: 'Quack quack! Daisy loves this song! Sing along with me!',
    category: 'song-intro',
    emotionTags: ['excited', 'playful'],
    contextTags: ['song-time'],
    ageGroup: '2-3',
    characterId: 'daisy',
    voiceProfileId: 'song-leader',
    ssml: ssml('Quack quack! <break time="200ms"/> Daisy loves this song! <break time="200ms"/> Sing along with me!', { rate: '108%', pitch: '+15%' }),
    priority: 1,
  },
  {
    id: 'song-003',
    text: 'Can you clap your hands to the beat? Clap, clap, clap! Let us sing!',
    category: 'song-intro',
    emotionTags: ['playful', 'excited'],
    contextTags: ['song-time'],
    ageGroup: 'all',
    voiceProfileId: 'song-leader',
    ssml: ssml('Can you clap your hands to the beat? <break time="300ms"/> Clap, clap, clap! <break time="200ms"/> Let us sing!', { rate: '105%', pitch: '+12%' }),
    priority: 2,
  },
  {
    id: 'song-004',
    text: 'This song teaches us something special. Listen carefully, then join in!',
    category: 'song-intro',
    emotionTags: ['warm', 'curious'],
    contextTags: ['song-time'],
    ageGroup: '4-5',
    voiceProfileId: 'song-leader',
    ssml: ssml('This song teaches us something special. <break time="400ms"/> Listen carefully, <break time="200ms"/> then join in!', { rate: '100%', pitch: '+10%' }),
    priority: 2,
  },
  {
    id: 'song-005',
    text: 'Here comes one of my favourite songs! I bet you will love it too. Ready?',
    category: 'song-intro',
    emotionTags: ['excited', 'warm'],
    contextTags: ['song-time'],
    ageGroup: 'all',
    voiceProfileId: 'song-leader',
    ssml: ssml('Here comes one of my favourite songs! <break time="300ms"/> I bet you will love it too. <break time="300ms"/> Ready?', { rate: '105%', pitch: '+12%' }),
    priority: 2,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STORY INTROS (5 lines)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'story-001',
    text: 'Once upon a time, in a land not so far away...',
    category: 'story-intro',
    emotionTags: ['warm', 'calm'],
    contextTags: ['story-time'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('Once upon a time, <break time="600ms"/> in a land not so far away...', { rate: '85%', pitch: '+3%' }),
    priority: 1,
  },
  {
    id: 'story-002',
    text: 'Are you sitting comfortably? Good. Then let us begin our story.',
    category: 'story-intro',
    emotionTags: ['warm', 'gentle'],
    contextTags: ['story-time'],
    ageGroup: 'all',
    characterId: 'ollie',
    voiceProfileId: 'narrator',
    ssml: ssml('Are you sitting comfortably? <break time="600ms"/> Good. <break time="400ms"/> Then let us begin our story.', { rate: '85%', pitch: '+3%' }),
    priority: 1,
  },
  {
    id: 'story-003',
    text: 'Hoot hoot! Ollie has a brand new story for you tonight. Come closer and listen.',
    category: 'story-intro',
    emotionTags: ['gentle', 'warm'],
    contextTags: ['story-time', 'bedtime'],
    ageGroup: 'all',
    characterId: 'ollie',
    voiceProfileId: 'bedtime-narrator',
    ssml: ssml('Hoot hoot! <break time="400ms"/> Ollie has a brand new story for you tonight. <break time="500ms"/> Come closer and listen.', { rate: '75%', pitch: '-3%', vol: 'soft' }),
    priority: 1,
  },
  {
    id: 'story-004',
    text: 'This story is about a brave little friend who goes on a big adventure. Sound familiar?',
    category: 'story-intro',
    emotionTags: ['curious', 'warm'],
    contextTags: ['story-time'],
    ageGroup: '4-5',
    voiceProfileId: 'narrator',
    ssml: ssml('This story is about a brave little friend who goes on a big adventure. <break time="500ms"/> Sound familiar?', { rate: '88%', pitch: '+5%' }),
    priority: 2,
  },
  {
    id: 'story-005',
    text: 'Get ready for a story full of surprises! You never know what might happen next.',
    category: 'story-intro',
    emotionTags: ['excited', 'curious'],
    contextTags: ['story-time'],
    ageGroup: '6-8',
    voiceProfileId: 'narrator',
    ssml: ssml('Get ready for a story full of surprises! <break time="400ms"/> You never know what might happen next.', { rate: '92%', pitch: '+8%' }),
    priority: 2,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // GOODBYES (8 lines)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: 'bye-001',
    text: 'Bye bye for now! You were amazing today. Come back soon!',
    category: 'goodbye',
    emotionTags: ['warm', 'proud'],
    contextTags: ['end-of-day'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('Bye bye for now! <break time="300ms"/> You were amazing today. <break time="300ms"/> Come back soon!', { rate: '90%', pitch: '+5%' }),
    priority: 1,
  },
  {
    id: 'bye-002',
    text: 'See you next time, superstar! I will be right here waiting for you.',
    category: 'goodbye',
    emotionTags: ['warm', 'gentle'],
    contextTags: ['end-of-day'],
    ageGroup: 'all',
    voiceProfileId: 'narrator',
    ssml: ssml('See you next time, superstar! <break time="400ms"/> I will be right here waiting for you.', { rate: '88%', pitch: '+3%' }),
    priority: 1,
  },
  {
    id: 'bye-003',
    text: 'ROAR! Great job today, friend! Leo cannot wait to see you again!',
    category: 'goodbye',
    emotionTags: ['warm', 'excited'],
    contextTags: ['end-of-day'],
    ageGroup: 'all',
    characterId: 'leo',
    voiceProfileId: 'mascot-host',
    ssml: ssml('<emphasis level="strong">ROAR!</emphasis> <break time="200ms"/> Great job today, friend! Leo cannot wait to see you again!', { rate: '100%', pitch: '+12%' }),
    priority: 2,
  },
  {
    id: 'bye-004',
    text: 'Time to go? Already? Well, you were wonderful. Bye bye!',
    category: 'goodbye',
    emotionTags: ['gentle', 'warm'],
    contextTags: ['end-of-day'],
    ageGroup: '2-3',
    voiceProfileId: 'narrator',
    ssml: ssml('Time to go? <break time="300ms"/> Already? <break time="400ms"/> Well, you were wonderful. <break time="200ms"/> Bye bye!', { rate: '85%', pitch: '+5%' }),
    priority: 2,
  },
  {
    id: 'bye-005',
    text: 'You learned so much today. Go and show everyone how clever you are!',
    category: 'goodbye',
    emotionTags: ['proud', 'warm'],
    contextTags: ['end-of-day', 'lesson-complete'],
    ageGroup: '4-5',
    voiceProfileId: 'narrator',
    ssml: ssml('You learned so much today. <break time="400ms"/> Go and show everyone how clever you are!', { rate: '92%', pitch: '+8%' }),
    priority: 2,
  },
  {
    id: 'bye-006',
    text: 'Until next time, adventurer! The world is lucky to have a learner like you.',
    category: 'goodbye',
    emotionTags: ['warm', 'proud'],
    contextTags: ['end-of-day'],
    ageGroup: '6-8',
    voiceProfileId: 'narrator',
    ssml: ssml('Until next time, adventurer! <break time="400ms"/> The world is lucky to have a learner like you.', { rate: '90%', pitch: '+5%' }),
    priority: 2,
  },
  {
    id: 'bye-007',
    text: 'Hop hop bye-bye! Ruby will miss you! Come back and play soon!',
    category: 'goodbye',
    emotionTags: ['playful', 'warm'],
    contextTags: ['end-of-day'],
    ageGroup: 'all',
    characterId: 'ruby',
    voiceProfileId: 'mascot-host',
    ssml: ssml('Hop hop bye-bye! <break time="200ms"/> Ruby will miss you! <break time="200ms"/> Come back and play soon!', { rate: '105%', pitch: '+15%' }),
    priority: 3,
  },
  {
    id: 'bye-008',
    text: 'Goodbye, my friend. Remember, every time you learn something new, a star lights up in the sky just for you.',
    category: 'goodbye',
    emotionTags: ['gentle', 'warm'],
    contextTags: ['end-of-day', 'bedtime'],
    ageGroup: 'all',
    characterId: 'ollie',
    voiceProfileId: 'bedtime-narrator',
    ssml: ssml('Goodbye, my friend. <break time="600ms"/> Remember, every time you learn something new, <break time="400ms"/> a star lights up in the sky <break time="300ms"/> just for you.', { rate: '75%', pitch: '-3%', vol: 'soft' }),
    priority: 2,
  },
];

// ── Lookup Helpers ─────────────────────────────────────────────────────────

/** O(1) lookup map for line by ID */
const lineById = new Map<string, VoiceLine>(voiceLines.map((l) => [l.id, l]));

/** Get a single line by its unique ID. */
export function getVoiceLineById(id: string): VoiceLine | undefined {
  return lineById.get(id);
}

/** Get all lines matching a category. */
export function getLinesByCategory(category: LineCategory): VoiceLine[] {
  return voiceLines.filter((l) => l.category === category);
}

/** Get lines matching category + optional emotion + optional context + optional age. */
export function queryVoiceLines(opts: {
  category?: LineCategory;
  emotion?: EmotionTag;
  context?: ContextTag;
  ageGroup?: AgeGroup;
  characterId?: string;
}): VoiceLine[] {
  return voiceLines.filter((line) => {
    if (opts.category && line.category !== opts.category) return false;
    if (opts.emotion && !line.emotionTags.includes(opts.emotion)) return false;
    if (opts.context && !line.contextTags.includes(opts.context)) return false;
    if (opts.ageGroup && line.ageGroup !== 'all' && line.ageGroup !== opts.ageGroup) return false;
    if (opts.characterId && line.characterId && line.characterId !== opts.characterId) return false;
    return true;
  });
}

/** Total line count, useful for analytics. */
export const totalVoiceLines = voiceLines.length;
